server:
  port: 8080
  
spring:
  application:
    name: greeting-service

logging:
  level:
#     root: WARN
     com.trsystems: INFO
     
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
  endpoint:
    health:
      show-details: ALWAYS        

greeting-service:
  greeting: "Hello"
  default-value: "World"
  
